language: go

os:
  - linux
  - osx

go:
  - 1.x

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
  - glide install

script:
  - go test -v $(go list ./... | grep -v /vendor/)
  